[window]
padding = { x = 12, y = 12 }
opacity = 0.9
blur = true

[font]
# AJUSTE AQUI: Use o nome que apareceu no comando fc-list acima
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
size = 11.0

[colors.primary]
background = "#2b3339" # Fundo verde escuro Everforest
foreground = "#d3c6aa" # Texto creme

[colors.normal]
black =   "#4b565c"
red =     "#e67e80"
green =   "#a7c080"
yellow =  "#dbbc7f"
blue =    "#7fbbb3"
magenta = "#d699b6"
cyan =    "#83c092"
white =   "#d3c6aa"

